site_name: Mazduino Documentation
nav:
  - Downloads: downloads.md
  - Quick Start: index.md
  - Compact 4 Channel:
    - v1: mazduino-compact-4ch-v1.md
    - v2.1: mazduino-compact-4ch-v2.1.md
    - v2.2: mazduino-compact-4ch-v2.2.md
  - Mini 6 Channel:
    - v1.0-v1.2: mazduino-mini-6ch-v1.0-v1.2.md
    - v1.3: mazduino-mini-6ch-v1.3.md
  - TunerStudio Manual: 
    - 'Manual Utama': 'tunerstudio-manual.md'
    - 'Pengaturan Output Controls': 'tunerstudio-output-controls.md'
    - 'Pengaturan Air Conditioning (A/C)': 'tunerstudio-ac-settings.md'
  - About: about.md
theme: 
  name: readthedocs